# Generated by Django 4.2.3 on 2024-01-25 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay6',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'De Active'), (2, 'Suspend'), (3, 'Block'), (4, 'Free')], default=4)),
                ('product_id', models.CharField(db_index=True, editable=False, max_length=22)),
                ('t1', models.JSONField()),
                ('t2', models.JSONField()),
                ('t3', models.JSONField()),
                ('t4', models.JSONField()),
                ('t5', models.JSONField()),
                ('t6', models.JSONField()),
                ('r1', models.BooleanField()),
                ('r2', models.BooleanField()),
                ('r3', models.BooleanField()),
                ('r4', models.BooleanField()),
                ('r5', models.BooleanField()),
                ('r6', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relay12',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'De Active'), (2, 'Suspend'), (3, 'Block'), (4, 'Free')], default=4)),
                ('product_id', models.CharField(db_index=True, editable=False, max_length=22)),
                ('r1', models.BooleanField()),
                ('r2', models.BooleanField()),
                ('r3', models.BooleanField()),
                ('r4', models.BooleanField()),
                ('r5', models.BooleanField()),
                ('r6', models.BooleanField()),
                ('r7', models.BooleanField()),
                ('r8', models.BooleanField()),
                ('r9', models.BooleanField()),
                ('r10', models.BooleanField()),
                ('r11', models.BooleanField()),
                ('r12', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
