# Generated by Django 4.1.1 on 2024-07-01 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=23)),
                ("image", models.ImageField(upload_to="device/image")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Psychrometer",
            fields=[
                (
                    "mod",
                    models.IntegerField(choices=[(1, "Thermometer"), (2, "Humidity")]),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=23)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Relay6",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("client_id", models.CharField(blank=True, max_length=55, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "De Active"),
                            (2, "Suspend"),
                            (3, "Block"),
                            (4, "Free"),
                        ],
                        default=4,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=11)),
                ("is_online", models.BooleanField(default=False)),
                ("r1", models.BooleanField()),
                ("r2", models.BooleanField()),
                ("r3", models.BooleanField()),
                ("r4", models.BooleanField()),
                ("r5", models.BooleanField()),
                ("r6", models.BooleanField()),
                (
                    "device_r1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r1",
                        to="device.device",
                    ),
                ),
                (
                    "device_r2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r2",
                        to="device.device",
                    ),
                ),
                (
                    "device_r3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r3",
                        to="device.device",
                    ),
                ),
                (
                    "device_r4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r4",
                        to="device.device",
                    ),
                ),
                (
                    "device_r5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r5",
                        to="device.device",
                    ),
                ),
                (
                    "device_r6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay6_device_r6",
                        to="device.device",
                    ),
                ),
                (
                    "t1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t1",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "t2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t2",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "t3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t3",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "t4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t4",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "t5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t5",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "t6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="t6",
                        to="device.psychrometer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Relay10",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("client_id", models.CharField(blank=True, max_length=55, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "De Active"),
                            (2, "Suspend"),
                            (3, "Block"),
                            (4, "Free"),
                        ],
                        default=4,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=11)),
                ("is_online", models.BooleanField(default=False)),
                ("r1", models.BooleanField()),
                ("r2", models.BooleanField()),
                ("r3", models.BooleanField()),
                ("r4", models.BooleanField()),
                ("r5", models.BooleanField()),
                ("r6", models.BooleanField()),
                ("r7", models.BooleanField()),
                ("r8", models.BooleanField()),
                ("r9", models.BooleanField()),
                ("r10", models.BooleanField()),
                ("name1", models.CharField(blank=True, max_length=39, null=True)),
                ("name2", models.CharField(blank=True, max_length=39, null=True)),
                ("name3", models.CharField(blank=True, max_length=39, null=True)),
                ("name4", models.CharField(blank=True, max_length=39, null=True)),
                ("name5", models.CharField(blank=True, max_length=39, null=True)),
                ("name6", models.CharField(blank=True, max_length=39, null=True)),
                ("name7", models.CharField(blank=True, max_length=39, null=True)),
                ("name8", models.CharField(blank=True, max_length=39, null=True)),
                ("name9", models.CharField(blank=True, max_length=39, null=True)),
                ("name10", models.CharField(blank=True, max_length=39, null=True)),
                (
                    "device_r1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r1",
                        to="device.device",
                    ),
                ),
                (
                    "device_r10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r10",
                        to="device.device",
                    ),
                ),
                (
                    "device_r2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r2",
                        to="device.device",
                    ),
                ),
                (
                    "device_r3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r3",
                        to="device.device",
                    ),
                ),
                (
                    "device_r4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r4",
                        to="device.device",
                    ),
                ),
                (
                    "device_r5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r5",
                        to="device.device",
                    ),
                ),
                (
                    "device_r6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r6",
                        to="device.device",
                    ),
                ),
                (
                    "device_r7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r7",
                        to="device.device",
                    ),
                ),
                (
                    "device_r8",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r8",
                        to="device.device",
                    ),
                ),
                (
                    "device_r9",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay10_device_r9",
                        to="device.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
