# Generated by Django 4.1.1 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay10",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="relay6",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
