# Generated by Django 4.2.3 on 2024-01-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay6',
            name='t1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t6',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
