# Generated by Django 4.2.3 on 2024-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relay10',
            name='device_r11',
        ),
        migrations.RemoveField(
            model_name='relay10',
            name='device_r12',
        ),
        migrations.AddField(
            model_name='relay10',
            name='name1',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name10',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name2',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name3',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name4',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name5',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name6',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name7',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name8',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='relay10',
            name='name9',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
