# Generated by Django 4.2.3 on 2024-01-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_relay6_t1_alter_relay6_t2_alter_relay6_t3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay6',
            name='product_id',
            field=models.CharField(db_index=True, max_length=22),
        ),
    ]
