# Generated by Django 4.1.1 on 2024-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_relay10_updated_at_alter_relay6_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay10",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relay6",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
