# Generated by Django 4.1.1 on 2024-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_relay10_updated_at_alter_relay6_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay10",
            name="device_id",
            field=models.CharField(db_index=True, max_length=110),
        ),
        migrations.AlterField(
            model_name="relay6",
            name="device_id",
            field=models.CharField(db_index=True, max_length=110),
        ),
    ]
