# Generated by Django 4.1.1 on 2024-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_remove_relay10_schedular_remove_relay6_schedular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relay10",
            old_name="product_id",
            new_name="device_id",
        ),
        migrations.RenameField(
            model_name="relay6",
            old_name="product_id",
            new_name="device_id",
        ),
    ]
