# Generated by Django 4.2.3 on 2024-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_relay6_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay12',
            name='product_id',
            field=models.CharField(db_index=True, max_length=22),
        ),
    ]
