# Generated by Django 4.1.1 on 2025-03-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_alter_relay10_device_id_alter_relay6_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay6",
            name="name1",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="relay6",
            name="name2",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="relay6",
            name="name3",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="relay6",
            name="name4",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="relay6",
            name="name5",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AddField(
            model_name="relay6",
            name="name6",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
