# Generated by Django 4.1.1 on 2024-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_rename_product_id_relay10_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay10",
            name="device_id",
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="relay6",
            name="device_id",
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
