# Generated by Django 4.1.1 on 2024-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_alter_relay10_device_id_alter_relay6_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay10",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="relay6",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
