# Generated by Django 4.1.1 on 2025-03-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_relay6_name1_relay6_name2_relay6_name3_relay6_name4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychrometer",
            name="current_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="destination_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="fluctuation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="hc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="ma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="on_of",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="plus_minus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="psychrometer",
            name="tolerance",
            field=models.IntegerField(default=0),
        ),
    ]
