# Generated by Django 4.2.3 on 2024-01-27 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_relay12_device_r1_relay12_device_r10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychrometer',
            fields=[
                ('mod', models.IntegerField(choices=[(1, 'Thermometer'), (2, 'Humidity')])),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=23)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t1', to='device.psychrometer'),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t2', to='device.psychrometer'),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3', to='device.psychrometer'),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4', to='device.psychrometer'),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t5', to='device.psychrometer'),
        ),
        migrations.AlterField(
            model_name='relay6',
            name='t6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t6', to='device.psychrometer'),
        ),
    ]
