# Generated by Django 4.1.1 on 2025-03-04 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_psychrometer_current_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychrometer",
            name="fluctuation",
        ),
        migrations.AlterField(
            model_name="relay6",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
