# Generated by Django 4.2.3 on 2024-01-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_psychrometer_alter_relay6_t1_alter_relay6_t2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay12',
            name='device_r1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r1', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r10', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r11', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r12', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r2', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r3', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r4', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r5', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r6', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r7', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r8', to='device.device'),
        ),
        migrations.AlterField(
            model_name='relay12',
            name='device_r9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay12_device_r9', to='device.device'),
        ),
    ]
