# Generated by Django 4.2.3 on 2024-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_relay12_device_r1_alter_relay12_device_r10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_id',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
