# Generated by Django 4.2.3 on 2024-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_remove_device_client_id_remove_relay12_r11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay12',
            name='schedular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relay6',
            name='schedular',
            field=models.BooleanField(default=False),
        ),
    ]
