# Generated by Django 4.1.1 on 2024-06-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_alter_relay10_device_id_alter_relay6_device_id"),
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetimer",
            unique_together={("relay10", "relay6", "relay_port_number")},
        ),
    ]
