# Generated by Django 4.1.1 on 2024-11-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0002_alter_devicetimer_updated_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetimer",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="devicetimer",
            name="days",
        ),
    ]
