# Generated by Django 4.1.1 on 2024-06-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_alter_relay10_device_id_alter_relay6_device_id"),
        ("timer", "0003_alter_devicetimer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetimer",
            unique_together={
                ("relay6", "relay_port_number"),
                ("relay10", "relay_port_number"),
            },
        ),
    ]
