# Generated by Django 4.2.3 on 2024-02-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagewarehouse',
            name='client',
        ),
    ]
