# Generated by Django 4.2.3 on 2023-07-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
    ]
